// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuLo7eoKQGoG2bOFXs6S9ls1mLPVHkc_M',
    appId: '1:627021658355:web:1b707a15c52f654e00df86',
    messagingSenderId: '627021658355',
    projectId: 'testebkpi',
    authDomain: 'testebkpi.firebaseapp.com',
    storageBucket: 'testebkpi.appspot.com',
    measurementId: 'G-07NPSE3K2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtW2YVdkc4KyLf2Xs5HKoMe-0H9t3RV3Q',
    appId: '1:627021658355:android:e38991a4988ecd9a00df86',
    messagingSenderId: '627021658355',
    projectId: 'testebkpi',
    storageBucket: 'testebkpi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd7NueOGlf3aGB5yc_Mkjy7UnZOlhhhRM',
    appId: '1:627021658355:ios:3f9fb8668cc44bc300df86',
    messagingSenderId: '627021658355',
    projectId: 'testebkpi',
    storageBucket: 'testebkpi.appspot.com',
    iosClientId: '627021658355-o15m6jkipss5glkmks7j3fotms2iarlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruithub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd7NueOGlf3aGB5yc_Mkjy7UnZOlhhhRM',
    appId: '1:627021658355:ios:3f9fb8668cc44bc300df86',
    messagingSenderId: '627021658355',
    projectId: 'testebkpi',
    storageBucket: 'testebkpi.appspot.com',
    iosClientId: '627021658355-o15m6jkipss5glkmks7j3fotms2iarlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruithub',
  );
}
